spring:
  main:
    banner-mode: off
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  batch:
    initialize-schema: always
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  password-strength: ${JWT_PASSWORD_STRENGTH}
  expiration-hours: ${JWT_EXPIRATION_HOURS}